name: Run sfkbot

on:
  workflow_dispatch:
  schedule:
    -كل 10 دقائق

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run sfkbot
        run: node index.js
